name = "agg-continents"
main = "src/index.ts"
compatibility_date = "2022-12-21"

[triggers]
crons = [ "*/5 * * * *" ]

[route]
pattern = "agg.ps2.live/continents*"
zone_name = "ps2.live"

[[kv_namespaces]]
binding = "CACHE"
id = "327612b58c854866a82a6d2bf5e2e0bc"
preview_id = "3351638a7f3c4104bf2e3764cebea64a"